/**
 * Print pipeline.
 *
 * Two adapters implement `PrintAdapter`:
 *  - `browserPrintAdapter` (here): builds a hidden print document from the
 *    rendered page SVGs and opens the system print dialog. Printer choice,
 *    copies and duplex are handled by the OS dialog.
 *  - The Electron adapter (apps/desktop) forwards to `webContents.print`,
 *    which adds silent printing, explicit printer selection and duplex flags.
 */
export interface PrintJob {
  /** One standalone SVG document per page, in order. */
  pageSvgs: string[];
  pageWidthMm: number;
  pageHeightMm: number;
  title: string;
  /**
   * @font-face CSS with data: URIs. The print document loads in an isolated
   * window/iframe with no access to the app's fonts, so handwriting fonts
   * must travel inside the document itself.
   */
  fontCss?: string;
}

export interface PrintOptions {
  /** Scale factor applied to each page (1 = 100%). */
  scale: number;
  /** Extra margins in mm added around the page content when scaling down. */
  margins: { top: number; right: number; bottom: number; left: number };
}

export const DEFAULT_PRINT_OPTIONS: PrintOptions = {
  scale: 1,
  margins: { top: 0, right: 0, bottom: 0, left: 0 },
};

export interface PrintAdapter {
  print(job: PrintJob, options: PrintOptions): Promise<void>;
}

/**
 * Build the standalone HTML print document for a job. Exposed separately from
 * the adapter so it is unit-testable and reusable by the Electron main process.
 */
export function buildPrintHtml(job: PrintJob, options: PrintOptions): string {
  const { pageWidthMm: w, pageHeightMm: h } = job;
  const pages = job.pageSvgs.map((svg) => `<div class="page">${svg}</div>`).join('\n');
  // Note: the SVGs are generated by our own export engine from escaped content;
  // no untrusted markup is interpolated here.
  return `<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>${escapeHtml(job.title)}</title>
<style>
  ${job.fontCss ?? ''}
  @page { size: ${w}mm ${h}mm; margin: ${options.margins.top}mm ${options.margins.right}mm ${options.margins.bottom}mm ${options.margins.left}mm; }
  html, body { margin: 0; padding: 0; }
  .page { width: ${w}mm; height: ${h}mm; page-break-after: always; overflow: hidden; }
  .page > svg { width: ${w * options.scale}mm; height: ${h * options.scale}mm; transform-origin: top left; }
  .page:last-child { page-break-after: auto; }
</style>
</head>
<body>${pages}</body>
</html>`;
}

/** Browser adapter: hidden iframe + window.print(). */
export const browserPrintAdapter: PrintAdapter = {
  async print(job, options) {
    if (typeof document === 'undefined') {
      throw new Error('browserPrintAdapter requires a browser environment.');
    }
    const iframe = document.createElement('iframe');
    iframe.style.position = 'fixed';
    iframe.style.right = '100%';
    iframe.style.width = '0';
    iframe.style.height = '0';
    iframe.setAttribute('aria-hidden', 'true');
    document.body.appendChild(iframe);
    try {
      const frameDoc = iframe.contentDocument;
      if (!frameDoc) throw new Error('Could not create print frame.');
      frameDoc.open();
      frameDoc.write(buildPrintHtml(job, options));
      frameDoc.close();
      await new Promise((resolve) => setTimeout(resolve, 150)); // allow fonts/layout
      iframe.contentWindow?.focus();
      iframe.contentWindow?.print();
    } finally {
      // Remove after the dialog closes; a delay avoids killing the job early.
      setTimeout(() => iframe.remove(), 60_000);
    }
  },
};

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
